### ISSUE TITLE
Zoom Tables

### ISSUE THREAD

**Issue by robertkeizer** [thlorenz/hhp#1]
Noticed that Zoom tables weren't being picked up. Tracked this down to a difference in the `_handInfoRx` regex.

The info line that I'm seeing is

```
PokerStars Zoom Hand #149651992548:  Hold'em No Limit ($0.02/$0.05) - 2016/07/03 21:11:35 ET
```

I originally thought this would be an easy issue and PR, simply add in optional regex bits for the `Zoom` etc. I am now thinking it might be a bit more complicated due to the `_handleInfoRx` being used to isolate variables in `_readInfo` to generate `this.hand.info`, in particular, the matching indices are used. Those indices are not the same between the two strings.

The only feasible way I can see adding zoom table support in, is if each module in `lib/holdem/` contains a function that returns `info`, rather than relying on `base` to perform this action based on a regex.

Thoughts?

**Comment by thlorenz** [comment]
I support Zoom tables now, see [these changes](https://github.com/thlorenz/hhp/compare/08607a37cee6e4e3bfd60df5e25993863f69c2a4...edf88bf12bc9373346e0ce56c3fd954ce1f69db5) which support all cash games.

To do this I allowed more flexibility WRT game info and table info regexes.
Please give it a try and LMK if things work for you now.
